export enum TicketType {
  ADULT_DIRECT = 'ADULT_DIRECT',
  ADULT_ZONAL = 'ADULT_ZONAL',
  ADULT_INTERZONAL = 'ADULT_INTERZONAL',
  STUDENT_DIRECT = 'STUDENT_DIRECT',
  STUDENT_ZONAL = 'STUDENT_ZONAL',
  STUDENT_INTERZONAL = 'STUDENT_INTERZONAL'
}
